### ISSUE TITLE
Undefined index: nameOfPoll

### ISSUE THREAD

**Issue by RastoJ** [Dzhus111/yii2-poll#2]
1. in ...\yiispct_protected\vendor\pollext\poll\views\index.php

<?php if((Yii::$app->user->getId()==null && $_POST['pollStatus']!='show' && $isVote == false ) || (**$_POST['nameOfPoll']**==$pollData['poll_name'] && $_POST['pollStatus']=='vote'&& $_POST['pollStatus']!='show' && Yii::$app->user->getId()==null)){

**Comment by Dzhus111** [comment]
Oh, thank you for issue. A long time I am not working with this repo. I did fast fix for this issue.
